spring:
  application:
    name: yun-api
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: "jdbc:mariadb://mariadb.cgnvzaiu4zsr.ap-northeast-2.rds.amazonaws.com:3306/yun?characterEncoding=UTF-8&serverTimezone=UTC"
    url: "jdbc:mariadb://localhost:3306/yun?characterEncoding=UTF-8&serverTimezone=UTC"
    username: root
    password: 1q2w3e!@#
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-befit-api
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    open-in-view: false
    show-sql: true
springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /**
